### ISSUE TITLE
Custom Color Grouping Crash

### ISSUE THREAD

**Issue by skyyyyboi** [johnpierson/MonocleForDynamo#11]
**What did you do?**
Tried to use custom color grouping from drop down menu (also happens with other tools, Doge is fine tho)

**What did you expect to see?**
the same pop up window as the previous version

**What did you see instead?**
crash report

**What packages or external references (if any) were used?**
none

**Stack Trace**

Initialization of 'Xceed.Wpf.Toolkit.ColorPicker' threw an exception.

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at MonocleViewExtension.ColorCodeGroups.ColorCodeWindow..ctor()
   at MonocleViewExtension.MonocleViewExtension.<>c__DisplayClass22_0.<Loaded>b__7(Object sender, RoutedEventArgs args)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**My setup**
OS: Microsoft Windows NT 10.0.18362.0
CLR: 4.0.30319.42000
Dynamo: 2.3.0.5885
Monocle:2020.06.19

**Comment by johnpierson** [comment]
Can you upload a screenshot of your package folder? Specifically the `bin `folder.

**Comment by skyyyyboi** [comment]
![packages](https://user-images.githubusercontent.com/67473421/85874848-41379200-b7a1-11ea-9fe9-e5f770635c2e.PNG)
![Monocle-bin](https://user-images.githubusercontent.com/67473421/85874850-41d02880-b7a1-11ea-891e-f58ab139f4e6.PNG)
![Monocle](https://user-images.githubusercontent.com/67473421/85874851-41d02880-b7a1-11ea-8d39-5180a3abc393.PNG)

**Comment by johnpierson** [comment]
Awesome. Thanks for the info. And to confirm, this is not happening if you download v.2020.6.1 ?

**Comment by skyyyyboi** [comment]
So the last updated I used was not 2020.6.1 when it was stable, it was a previous version, before the align pop up appear when you select multiple nodes on the canvas.

I deleted 6.19, opened a new session of Revit, opened dynamo, installed 6.1, close dynamo and then reopened to get monocle to load, and everything was good, i can access custom color without a crash. Then i closed revit, reopened a new session, new file, dynamo, and the crash happened again.

Would you like me to go back though the releases until i find the one that was working?

**Comment by skyyyyboi** [comment]
I installed the release that was working was around 3/18/2020

**Comment by skyyyyboi** [comment]
After deleteing all packages, seems to fix the issues, Works after restarting revit and remembers color changes set in previous dynamo session.

![color01](https://user-images.githubusercontent.com/67473421/86814897-fa268800-c04f-11ea-92e4-a0fb4982006f.PNG)

**Comment by johnpierson** [comment]
That's good to hear! Definitely let me know when you hit a package that causes the issue so I can replicate it.  😁

**Comment by skyyyyboi** [comment]
![UI++](https://user-images.githubusercontent.com/67473421/86834513-ecc9c780-c068-11ea-9cbb-7cc9a98952c6.PNG)

I found the culprit. Naturally it was the second last package. I also had someone else on the team test and it broke it for him too.

**Comment by johnpierson** [comment]
AHHHHHH ok awesome. This is good news actually. Because that package is obsolete and is OOTB now. The new node is called "Color Palette"

**Comment by johnpierson** [comment]
This should be fixed in v.2020.7.7
