### ISSUE TITLE
Could not load file or assembly 'WpfAnimatedGif,

### ISSUE THREAD

**Issue by chuongmep** [johnpierson/MonocleForDynamo#37]
**Describe the bug**
Could not load file or assembly 'WpfAnimatedGif, PublicKeyToken=9e7cd3b544a090dc' or one of its dependencies. The system cannot find the file specified.

   at System.Windows.Markup.XamlReader.RewrapException(Exception e, IXamlLineInfo lineInfo, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)
   at System.Windows.Markup.WpfXamlLoader.LoadBaml(XamlReader xamlReader, Boolean skipJournaledProperties, Object rootObject, XamlAccessLevel accessLevel, Uri baseUri)
   at System.Windows.Markup.XamlReader.LoadBaml(Stream stream, ParserContext parserContext, Object parent, Boolean closeStream)
   at MonocleViewExtension.PackageUsage.PackageUsageCommand.<>c__DisplayClass0_0.<AddMenuItem>b__0(Object sender, RoutedEventArgs args)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)

-------- InnerException --------

Could not load file or assembly 'WpfAnimatedGif, PublicKeyToken=9e7cd3b544a090dc' or one of its dependencies. The system cannot find the file specified.

   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.Assembly.Load(AssemblyName assemblyRef)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveAssembly(BamlAssembly bamlAssembly)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlTypeToType(BamlType bamlType)
   at System.Windows.Baml2006.Baml2006SchemaContext.ResolveBamlType(BamlType bamlType, Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetXamlType(Int16 typeId)
   at System.Windows.Baml2006.Baml2006SchemaContext.GetProperty(Int16 propertyId, XamlType parentType)
   at System.Windows.Baml2006.Baml2006Reader.Process_PropertyComplexStart()
   at System.Windows.Baml2006.Baml2006Reader.Process_OneBamlRecord()
   at System.Windows.Baml2006.Baml2006Reader.Process_BamlRecords()
   at System.Windows.Baml2006.Baml2006Reader.Read()
   at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector)
   at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri)

-------- Assemblies --------

mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|DynamoSandbox, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|DynamoCore, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|PresentationFramework, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|WindowsBase, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|PresentationCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|System.Xaml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|DynamoApplications, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|DynamoInstallDetective, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|System.Configuration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|DynamoServices, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51|NDesk.Options, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null|System.Xml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|DynamoCoreWpf, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Microsoft.Practices.Prism, Version=4.1.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|SharpDX.Mathematics, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|DynamoShapeManager, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|LibG.AsmPreloader.Managed, Version=2.13.0.8745, Culture=neutral, PublicKeyToken=null|LibG.AsmPreloader.Unmanaged, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null|Greg, Version=2.3.0.1646, Culture=neutral, PublicKeyToken=null|ProtoCore, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|DynamoUtilities, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|ProtoAssociative, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|ProtoImperative, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Analytics.Net.ADP, Version=2.13.0.0, Culture=neutral, PublicKeyToken=null|Analytics.NET.Core, Version=2.13.0.24836, Culture=neutral, PublicKeyToken=null|Analytics.NET.Google, Version=2.13.0.24837, Culture=neutral, PublicKeyToken=null|AdpSDKCSharpWrapper, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|CSharpAnalytics.Net45, Version=1.2.0.0, Culture=neutral, PublicKeyToken=null|System.Runtime.Serialization, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|SMDiagnostics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.ServiceModel.Internals, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|DynamoUnits, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|DynamoCore.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|System.Net.Http, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Newtonsoft.Json, Version=8.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed|DynamoPackages, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.Drawing, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|DesignScriptBuiltin, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|VMDataBridge, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|ProtoCore.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Anonymously Hosted DynamicMethods Assembly, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null|System.Dynamic, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|ProtoGeometry, Version=2.13.0.8745, Culture=neutral, PublicKeyToken=null|LibG.Interface, Version=2.13.0.8745, Culture=neutral, PublicKeyToken=null|DSCoreNodes, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|DSCoreNodes.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|DSOffice, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|DSOffice.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|DSCPython, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Python.Runtime, Version=2.5.2.4265, Culture=neutral, PublicKeyToken=null|DynamoConversions, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Tessellation, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|MIConvexHull.NET Standard, Version=1.0.17.411, Culture=neutral, PublicKeyToken=null|System.Runtime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Analysis, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Analysis.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|GeometryColor, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|ProtoScript, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|LibG.ProtoInterface, Version=2.13.0.8745, Culture=neutral, PublicKeyToken=null|LibG.Managed, Version=2.13.0.8745, Culture=neutral, PublicKeyToken=null|CoreNodeModels.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|CoreNodeModels, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|CoreNodeModels.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|CoreNodeModelsWpf, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|GeometryUI.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|GeometryUI, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|GeometryUI.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|GeometryUIWpf, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Migrations, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|NCalc, Version=1.3.8.0, Culture=neutral, PublicKeyToken=973cde3f1cafed03|PythonNodeModels.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|PythonNodeModels, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|PythonNodeModels.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|PythonNodeModelsWpf, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|ICSharpCode.AvalonEdit, Version=4.3.1.9429, Culture=neutral, PublicKeyToken=9cc39be672370310|UnitsUI.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|UnitsUI, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|UnitsUI.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|Watch3DNodeModels.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Watch3DNodeModels, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Watch3DNodeModels.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|Watch3DNodeModelsWpf, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Xceed.Wpf.Toolkit, Version=3.0.0.0, Culture=neutral, PublicKeyToken=3e4669d2f30244f4|System.Xml.Linq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|BuiltIn.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Operators.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|ProtoGeometry.customization, Version=2.13.0.8745, Culture=neutral, PublicKeyToken=null|DesignScriptBuiltin.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|DSCoreNodes.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|DSOffice.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|DynamoUnits.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Tessellation.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Analysis.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|GeometryColor.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|RestSharp, Version=106.12.0.0, Culture=neutral, PublicKeyToken=598062e77f915f75|DynamoPackages.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|System.Numerics, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.Data, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|DynaWorks22, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Interop.NavisworksIntegratedAPI19, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Interop.NavisworksAutomationAPI19, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|Exyte, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|QRCoder, Version=1.3.7.0, Culture=neutral, PublicKeyToken=null|QRImage.customization, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|QRImage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|HelixToolkit.Wpf.SharpDX, Version=2.17.0.0, Culture=neutral, PublicKeyToken=52aa3500039caf0d|SharpDX, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|DynamoCoreWpf.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|HelixToolkit, Version=2.17.0.0, Culture=neutral, PublicKeyToken=52aa3500039caf0d|SharpDX.DXGI, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|SharpDX.Direct3D11, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|SharpDX.Direct2D1, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|FontAwesome.WPF, Version=4.7.0.37774, Culture=neutral, PublicKeyToken=0758b07a11a4f466|PresentationFramework.Aero2, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|PresentationFramework-SystemXml, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|UIAutomationTypes, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|UIAutomationProvider, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|DocumentationBrowserViewExtension, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|DocumentationBrowserViewExtension.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|DynamoManipulation, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|GraphMetadataViewExtension, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|GraphNodeManagerViewExtension, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|LibraryViewExtensionMSWebBrowser, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|LintingViewExtension, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|Notifications, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|PackageDetailsViewExtension, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|DynamoPackagesWPF, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|PythonMigrationViewExtension, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|WorkspaceDependencyViewExtension, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|WorkspaceDependencyViewExtension.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|GraphMetadataViewExtension.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|GraphNodeManagerViewExtension.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|LintingViewExtension.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|Notifications.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|PackageDetailsViewExtension.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|PresentationFramework-SystemXmlLinq, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|PresentationFramework-SystemCore, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|Dynamo.Microsoft.Xaml.Behaviors, Version=1.1.0.0, Culture=neutral, PublicKeyToken=null|PresentationFramework-SystemData, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|LibraryViewExtensionMSWebBrowser.resources, Version=2.15.0.5383, Culture=en-US, PublicKeyToken=null|System.Web, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Cyotek.Drawing.BitmapFont, Version=1.0.0.0, Culture=neutral, PublicKeyToken=58daa28b0b2de221|WindowsFormsIntegration, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35|SharpDX.D3DCompiler, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|SharpDX.Direct3D9, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b4dcf0f35e5521f1|Microsoft.mshtml, Version=7.0.3300.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Accessibility, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|Windows.UI, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime|System.Runtime.InteropServices.WindowsRuntime, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|System.IO.Compression.FileSystem, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089|MonocleViewExtension, Version=2022.9.1.0, Culture=neutral, PublicKeyToken=null|Microsoft.GeneratedCode, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null|DynamoCore.customization, Version=2.15.0.5383, Culture=neutral, PublicKeyToken=null|System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|System.Runtime.Extensions, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a|System.Resources.ResourceManager, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a

**Steps to Reproduce**
- Dowload last version 2022.9.1
- Use Dynamo Core Version 2.15.0.5383
- Click to location show in image bellow
![ảnh](https://user-images.githubusercontent.com/31106432/190530788-7b79b0fc-af71-4d97-a563-b0698733f671.png)

**Expected behavior**
(Please fill in. A clear and concise description of what you expected to happen.)

**My setup**
- Operating System: Window 10
- Dynamo version: 2.15.0.5383
- Monocle version: 2022.9.1
- Revit version: None

**Comment by johnpierson** [comment]
Whoops. I forgot to include that dependency in the latest package. Will fix asap. For now use boring mode. 😁
